# Generated by Django 3.1 on 2022-03-22 22:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('interest', models.FloatField(max_length=2)),
                ('term', models.IntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('amount_average', models.FloatField(default=0.0)),
                ('interest_average', models.FloatField(max_length=2)),
                ('date', models.DateField(default=datetime.date(2022, 3, 22))),
            ],
        ),
    ]
