# Generated by Django 3.1 on 2022-03-23 00:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(default=datetime.date(2022, 3, 23)),
        ),
    ]
